apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lqoaUbNF,iv:vKwPlhENKOgV9akrXoYx8XID8F89dZH6Z4+qnIvbM1Q=,tag:uBVU7rrwOCr8bof4MC1pcQ==,type:str]
    password: ENC[AES256_GCM,data:FjkkQRDIqPZnaXq3JJ/o,iv:6TLBL5qpdPs65n/vJq2rSQxpO7PPUt3MZaD/+3o6J3Y=,tag:nOIypmtqgk8ExoN73/HI7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sydzscuxes5gt386z9lvszf0unc793fd7rq6d4puum5xyqsud4hslach78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWFQwY3djZTUzZHNzTW1V
            YjBHZy83N0FxaHRNSjRSTHJSdGlHOUtCZG1FCkhxd25NeHYzVEdqRDJzWldlZWxs
            b1JQaFZ5VnFjNnplWW1hdkhndGJQdTgKLS0tIFhLeC8xa2pXY0xBczQ2aGllendL
            S290dld5QkFwQzBGUUtLV2pvL0VxT3cKEw9y5DyYSLg4BlPX9yfQY/YRHTv4JDZ0
            tSTOyRsZCNt4gxEWk4qhuQWaZxrJLMTeBzn1JZKS/TTvNRXHNBWPsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T01:52:36Z"
    mac: ENC[AES256_GCM,data:9BpLUavPU9CMtF0PXIKmjC+zx3YGKlKb8tAAnMzk0i7WyqUA4sVd5CucBeEVqnsc8Of51lDgSoBDVpWOCMeeGpAK0oU0GfPhuYt6jWA3jEKsBCXsNvA82mt8yF+iXJvyMNrAkaNOVQeYGQsX4p+2oXwuKQiSLcXsmddf40TXeG4=,iv:AMlPIB7TsvYgYhXQZT/+lfr7Qd46Y3jeQ8Sf+1hWb3w=,tag:196ucryvZ+2R7isjOgCYhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
