[tools]
go = "latest"
golangci-lint = "latest"
kotlin = "latest"
gradle = "latest"
graalvm = "latest"
docker-cli = "latest"
docker-compose = "latest"


[settings]
experimental = true
auto_install = true

[tasks]
start = "docker compose up"
start-dev = "docker compose up --build"
