[tools]
go = "latest"
golangci-lint = "latest"
kotlin = "latest"
gradle = "latest"
graalvm = "latest"
docker-cli = "latest"
docker-compose = "latest"
node = "20"
gomigrate = "latest"
goreleaser = "latest"
gitversion = "latest"
gh = "latest"

[settings]
experimental = true
auto_install = true
