---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: beacon
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: digest
  applicationRefs:
    - namePattern: api
      images:
        - alias: api
          imageName: ghcr.io/sverdejot/beacon/api:latest
    - namePattern: ingester
      images:
        - alias: ingester
          imageName: ghcr.io/sverdejot/beacon/ingester:latest
    - namePattern: feed
      images:
        - alias: feed
          imageName: ghcr.io/sverdejot/beacon/feed:latest
    - namePattern: dashboard
      images:
        - alias: dashboard
          imageName: ghcr.io/sverdejot/beacon/dashboard:latest
