apiVersion: v1
kind: Secret
metadata:
  name: plausible-credentials
  namespace: beacon
type: Opaque
stringData:
  database-url: postgres://plausible:plausible@plausible-db:5432/plausible
  clickhouse-database-url: http://plausible-events-db:8123/plausible
  secret-key-base: CHANGE_ME_BEFORE_DEPLOYING
